### ISSUE TITLE
Question: Using Reactor streams 

### ISSUE THREAD

**Issue by pckeyan** [reactor/reactive-streams-commons#24]
Hi, I am from a Financial Organization. have multiple use cases to use stream processing to send alerts and notifications to customers. We are interested in reactor-streams and I came to this project. I understand it is the second generation of Reactor Streams. Please confirm and let me know when is the targeted release for this project to be consumed for production?

Please share if you have any documentation like user guide that would be helpful.

Thanks and Regards
Karthik

**Comment by akarnokd** [comment]
Hi. This is a research project and the primary benefactor is https://github.com/reactor/reactor-core which I guess you were looking for.

We don't have any release schedule and the aim is to explore ideas around 4th generation reactive dataflows. It is not recommended for production use and has otherwise quite high entry barrier for contributions.

**Comment by pckeyan** [comment]
Thanks and Appreciate your quick turnaround. Can you please confirm whether reactor-stream in 2.0.8 Release is merged with Reactor-Core 2.5 Snapshot M4?

**Comment by akarnokd** [comment]
Probably never; 2.5 is abandoning/redoing almost everything from 2.0.x series, new architecture, new internals, etc. I'm not involved in those level of decisions regarding Reactor-Core; you should ask your further questions over there.
